print ('Tabuada')
n = int(input('Informe o valor: '))
print('0 X',n,'=',n*0)
print('1 X',n,'=',n*1)
print('2 X',n,'=',n*2)
print('3 X',n,'=',n*3)
print('4 X',n,'=',n*4)
print('5 X',n,'=',n*5)
print('6 X',n,'=',n*6)
print('7 X',n,'=',n*7)
print('8 X',n,'=',n*8)
print('9 X',n,'=',n*9)
print('10 X',n,'=',n*10)
